### ISSUE TITLE
Flush equation left

### ISSUE THREAD

**Issue by phkonzen** [brucemiller/LaTeXML#2121]
I would like to have flushed left equations in HTML output. The following minimal example
```
\documentclass{article}

\usepackage[fleqn]{amsmath}

\begin{document}
\begin{equation}
  x^2 = 1
\end{equation}

\begin{align}
  x^2 &= 1\\
  x &= \pm 1
\end{align}
\end{document}

```
When compiled with
`latexml main.tex | latexmlpost --format=html -dest=main.html -`
produce horizontal center equations.

Is there any workaround?

**Comment by dginev** [comment]
@phkonzen if you want to achieve this for all equations on the page, while using the currently generate HTML from latexml, you can add a new CSS rule that hides the left padding, as in:

```css
td.ltx_eqn_center_padleft {
    display: none;
}
```

But this will apply to **all** equations, without exception. If you want to only left-align equations coming from `{align}` the CSS would be:

```css
table.ltx_eqn_align td.ltx_eqn_center_padleft {
    display: none;
}
```

Generally the concrete styling questions are often best addressed in CSS, while the main latexml conversion has the responsibility of providing enough hooks for writing the correct rules.
