### ISSUE TITLE
/align Has a lot of whitespace in mathml output

### ISSUE THREAD

**Issue by orbita2d** [brucemiller/LaTeXML#2388]
```latex
\begin{align}
A &=& \cos\theta &+& \sin\theta \\
  &=& D &+& F
\end{align}
```

renders like
![capture2024-08-10T14:52:51](https://github.com/user-attachments/assets/3cf034de-b40b-4fbe-bc99-24de4b2edc44)

because of LaTeXML.css:133

```css
table.ltx_eqn_align tr.ltx_equation td.ltx_align_left + td.ltx_align_right { padding-left:3em; }
```

I'm not sure what it's trying to do.
