### ISSUE TITLE
make the html references language-independent

### ISSUE THREAD

**Issue by kohlhase** [brucemiller/LaTeXML#804]
This is a variant of #803. It would be good if the html references were language indepdendent. LaTeXML currently generates e.g. 
```XML
<span class="ltx_bibblock ltx_bib_cited">Cited by: <a href="#p1" title="" class="ltx_ref">p1</a>.</span>
```
It would be much better to have the language independent 
```XML
<span class="ltx_bibblock ltx_bib_cited"><a href="#p1" title="" class="ltx_ref">p1</a></span>
```
and add to the CSS something like 
```CSS
span.ltx_bib_cited::before {content:"Cited by: "}
span.ltx_bib_cited::after {content: "."}
```
Then that can be overridden by a language-specific CSS file if needed. 
An analogous situation is with 
```
<span class="ltx_bibblock">External Links: <span class="ltx_text ltx_bib_links"><span class="ltx_text isbn ltx_bib_external">ISBN 978-3-642-21033-4</span></span>
</span>
```
